### ISSUE TITLE
Consider changing compose & apply to accept a variable number of arguments

### ISSUE THREAD

**Issue by joshburgess** [mostjs/prelude#20]
While attempting to use `@most/prelude`'s compose function to make my own `switchMap`, like 
```
import { map, switchLatest } from 'most'
import { compose } from '@most/prelude'
const switchMap = compose(switchLatest, map)
```

I ran into an error and realized it was because map needs to take in multiple arguments. I got around the problem by writing my own compose function in the library, like this:

```
const compose2 = (f, g) => (...args) => f(g(...args))
const switchMap = compose2(switchLatest, map)
```

And we could do the same with apply:

```
const apply = (f, ...args) => f(...args)
```
or maybe 
```
const applyArray = (f, argsArr) => f(...argsArr)
```

I realize I could still accomplish the same things by using prelude's compose/apply + the curry functions, but it would require additional steps and would be less convenient.

We could also add partial application: 

```
const partial = (f, ...args) => (...rest) => f(...args, ...rest)
```

And it might be more than what's wanted or is necessary for prelude, but we could go further by defining a `fold1` to help create a variadic `compose`:

```
// like foldl1 in Haskell
const fold1 = (f, arr) => {
  if (!arr.length) {
    throw Error('fold1 must only be applied to non-empty lists')
  }

  let acc

  for (let i = 0; i < arr.length; i++) {
    acc = !acc ? arr[i] : f(acc, arr[i])
  }

  return acc
}

const compose2 = (f, g) => (...args) => f(g(...args))

// compose function for when the function arity is unknown
const compose = (...fs) => fold1(compose2, fs)
```

Thoughts on changing and/or adding any of these?

**Comment by davidchase** [comment]
@joshburgess great topic for discussion

Personally I prefer non-variadic functions especially when it comes to typing just look at the Ramda's [compose](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/868b7fa0e1aae75347a1744fc0f5f585da9cf2d5/types/ramda/index.d.ts#L300-L322) in TypeScript. Also not easy or really possible to curry variadic functions.

I like enforcing rigorous standards from a libraries POV... if end user wants compose/et al to be variadic they should have the freedom but the library should enforce a specific arity.

Sometimes I make my own `const composeAll = (...fns) => fns.reduce(compose2)` i feel like its good practice and not much work on my end...

I also kinda like that this prelude pays tribute if you will to Haskell's prelude only we cant name `compose` and `apply` like so: `.`  `$` in JS land

/cc @briancavalier @TylorS

**Comment by joshburgess** [comment]
@davidchase what do you think about prelude's current `compose` function? It only accepts 1 argument. 

```
const compose = (f, g) => x => f(g(x))
```

However, if it were

```
const compose = (f, g) => (...args) => f(g(...args))
```

there would be no change in usefulness as far as currying/partial application goes, but it would then allow the `g` function to accept any number of arguments, while still being explicit about only composing two functions together. We could have specific arity versions, like:

```
const compose2 = (f, g) => (...args) => f(g(...args))
const compose3 = (f, g, h) => (...args) => f(g(h(...args)))
const compose4 = (f, g, h, i) => (...args) => f(g(h(i(...args))))
```

**Comment by davidchase** [comment]
> It only accepts 1 argument.

I think this looks kinda nice:

```js
import { map, switchLatest, runEffects, tap } from '@most/core'
import { newDefaultScheduler } from '@most/scheduler'
import { compose } from '@most/prelude'

const switchMap = f => compose(map(f), switchLatest)
const inc = switchMap(x => x + 1)
const observe = stream => runEffects(tap(log, stream), newDefaultScheduler())

observe(inc(highOrderStream))
```

since `map` is curried from prelude there is no problem that `compose` only taking in a single argument

what are your thoughts @joshburgess  ?

**edit** sorry `map` is curried from `@most/core` not `@most/prelude`

**Comment by briancavalier** [comment]
Hey @joshburgess, good discussion here.  I figured it might be helpful to provide a little history and motivation behind `@most/prelude`.  Sorry, we haven't done a good job of documenting this stuff in the README.

Since `most` had a focus on performance, we wanted performance-oriented basic FP functions we could use within the `most` codebase.  We also wanted immutability for array ops.  In fact, `@most/prelude` started out as just a module buried inside `most`.  So, we created functions that filled our basic FP needs, provided immutability, and, in general, performed at least as well as builtin analogs.  It was never intended to be a lodash or ramda alternative--we don't currently have the resources to support something like that.

And now back to some of the questions in this thread.

Switching `compose` to varargs isn't free.  The extra `arguments`/`Array` copy, and the fact compilers will tend to use `.apply`, means there is a non-trivial performance hit.  That can be avoided by using a more complex implementation of `compose` (one that uses `arguments` directly and dispatches with a `switch` statement, for example), but then we're adding complexity.  The simplicity of the current compose is pretty compelling and has served our needs in developing `most`.

What do you see as the compelling reasons to make that tradeoff vs. what @davidchase showed above with `switchMap`?

As far as expanding the scope of `@most/prelude` to include more utilities, I think our goal remains the same: satisfy the basic needs of `most` and `@most/core` development.  So, if we have use cases for adding `partial`, `foldl1`, etc, then I'm cool with it.  It's a bit of slippery slope into lodash/ramda land, tho, so we need to be careful.

Perhaps someone could create a `@most/prelude` companion package that provides a larger set of operations and/or varargs versions where appropriate.

**Comment by joshburgess** [comment]
@briancavalier Ah, okay. Understood. Yeah, I just figured I could use prelude's `compose`, because I was writing a library that already made use of `most` & `most-subject` and had removed all use of Ramda within the library, as I was trying to cut down on my build size. It might be better for me just to write some one off functions and stick them in a utils folder or rewrite with `@most/core`. 

I'm still using `most`. That's one reason why I didn't do something along the lines of what @davidchase suggested.... I would have had to also import or write a curry function to curry the `map`... 

```
const curriedMap = curry2(map)
```

and to make use of the switchMap function, I'd have to define it in the scope where I had access to the variables I needed for the function that gets passed into map or, instead, do something like 

```
const switchMap = f => stream => compose(switchLatest, curriedMap(f))(stream)
```
or
```
const switchMap = curry2((f, stream) => compose(switchLatest, curriedMap(f))(stream))
```

in order to make it generic/reusable enough to define somewhere else (like tucked away in a utils folder somewhere).

I guess I was just still thinking about it in an RxJS sort of mindset. Quick question about what you said regarding performance, if 

```
const compose2 = (f, g) => (...args) => f(g(...args))
```

was rewritten as

```
const compose2 = (f, g) => (argsArray) => f(g(...argsArray))
```

would it still have the same performance drawback? Not asking for `prelude`... just asking for myself, so that I know if I write my own one off functions in the library.

Also, is `@most/core` stable and ready to be used? I like the idea of it focusing on the functional style (as opposed to fluent/chaining) and being auto-curried like lodash/fp & ramda. Is it intended to be used directly or will those things be exposed by `most` at some point?

**Comment by briancavalier** [comment]
> I'm still using most. That's one reason why I didn't do something along the lines of what @davidchase suggested

Yeah, sadly, `most` isn't tree shakeable atm because of prototypes (prototype-based libraries in general aren't tree-shakeable).

> in order to make it generic/reusable enough to define somewhere else (like tucked away in a utils folder somewhere).

This'll work:

```js
const switchMap = curry2((f, stream) => switchLatest(map(f, stream)))
```

I don't think it can be done entirely point-free (i.e. without mentioning `stream`) with current JS currying techniques, but that version isn't too bad.  It may be possible with [a different currying technique](https://gist.github.com/briancavalier/45617b0210dbc1023421837b7da4ad11), but I haven't tried.

> would it still have the same performance drawback?

Less of a hit, I think.  It avoids the `arguments` -> `array` copy, but would likely still end up being compiled to use `.apply`, so that hit would remain.  A smart compiler should notice be able to optimize things of the form `f(...args) => g(...args)` (like your previous example) to avoid the `arguments` -> `array` and just do `.apply(this, arguments)`.  A highly optimizing compiler would probably try to turn it into a `switch()` statement that dispatches on `arguments.length`.  I don't know if the current generation of babel and/or buble (or any respective plugins) do either of those things, tho.

> Also, is @most/core stable and ready to be used?

It's definitely usable.  Since it's < 1.0, though, it's certainly possible that we'll have breaking API changes (none are *planned* atm).  There's no documentation (except the source code!), and there are some differences/incompatibilities with `most` and some `@most/*` packages (notably `@most/dom-event`.

So, I can't recommend it for production just yet, but for personal projects, yeah, I think it's viable.  We're happy to help and answer questions if you give it a go.

> Is it intended to be used directly or will those things be exposed by most at some point?

Our goal is both.  It'll be usable directly, and `most` 2.0 will be built upon it.

Hope that helps!

**Comment by joshburgess** [comment]
@briancavalier Cool. Thanks for all the info. We can close this now, and I'll check out `@most/core` soon.
