### ISSUE TITLE
Why not using Ramda?

### ISSUE THREAD

**Issue by joaomilho** [mostjs/prelude#6]
This would add some kb for sure, but the work there seems pretty solid and follows Fantasy Land. WDYT?

**Comment by briancavalier** [comment]
Hi @joaomilho.  I'm a big fan of Ramda, and have recommended it using it with most--they work together quite well because both support Fantasy Land.  However, `@most/prelude` and Ramda have different priorities and goals.  Ramda is a great end-user FP lib.  `@most/prelude`'s top priority is to serve the _internal_ needs of most.js and `@most/...` packages.  That way it can stay smaller, and provide maximum performance for the narrow use cases inside of most.

For example, `@most/prelude`'s map, reduce, etc. only need to support arrays, and not also iterables and transducers, as Ramda's do.  Another example: `@most/prelude`'s public API is intentionally uncurried, to avoid the (small) overhead of calling curried functions in JS.

The size difference is also substantial.  Ramda is larger than all of most.js, currently.  I realize it's possible to do custom builds of Ramda, but prelude is less than 1kb gzipped currently.

```
-rw-r--r--  1 brian  staff     950 Apr 28 15:20 prelude.min.js.gz

-rw-r--r--  1 brian  wheel   11444 May  9 08:36 ramda.min.js.gz

-rw-r--r--  1 brian  staff   11252 May  6 07:28 most.min.js.gz
```

So, for now, we'll stick with prelude.
